#!/bin/bash
TARGET="${1:-.}"
echo "== AWS Access Keys =="
grep -roPn '\b(AKIA|ASIA)[0-9A-Z]{16}\b' "$TARGET"
echo "== GitHub Tokens =="
grep -roPn '\b(ghp|gho|ghu|ghs|ghr|github_pat)_[A-Za-z0-9_]{36,255}\b' "$TARGET"
echo "== Google API Keys =="
grep -roPn '\bAIza[0-9A-Za-z\-_]{35}\b' "$TARGET"
echo "== Slack Tokens =="
grep -roPn '\bxox[baprs]-[A-Za-z0-9-]{10,72}\b' "$TARGET"
echo "== JWTs =="
grep -roPn '\bey[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b' "$TARGET"
echo "== Private Key Headers =="
grep -rnE -- '-----BEGIN (RSA |EC |OPENSSH |DSA |PGP )?PRIVATE KEY-----' "$TARGET"
echo "== Generic key/secret/token assignments =="
grep -roPn '(?i)(api[_-]?key|secret|token|access[_-]?key|client[_-]?secret)["\047]?\s*[:=]\s*["\047][A-Za-z0-9_\-]{16,}["\047]' "$TARGET"
